// import React from 'react';
const Decimal = require('decimal.js');

export default function BusinessInit() {

    return ([
        {
            name: "Odd Jobs",
            desc: "desc1",
            owned: 1,
            incomeType: "money",
            incomeBase: new Decimal(1),
            costType: "money",
            costBase: new Decimal(10),
            costCoef: 1.07,
            timeBase: 1,
            timeAdjusted: 1,
            timeCounter: 0,
            payout: false,
            initialVisible: new Decimal(0),
            upgradeMult: 1,
            upgradeAdd: 0,
            revealed: false,
            overlays: [],
        }, {
            name: "Newspaper Delivery",
            desc: "desc2",
            owned: 0,
            incomeType: "money",
            incomeBase: new Decimal(50),
            costType: "money",
            costBase: new Decimal(75),
            costCoef: 1.15,
            timeBase: 2,
            timeAdjusted: 2,
            timeCounter: 0,
            payout: false,
            initialVisible: new Decimal(500),
            upgradeMult: 1,
            upgradeAdd: 0,
            revealed: false,
            overlays: [],
        }, {
            name: "Car Wash",
            desc: "desc2",
            owned: 0,
            incomeType: "money",
            incomeBase: new Decimal(2500),
            costType: "money",
            costBase: new Decimal(750),
            costCoef: 1.14,
            timeBase: 4,
            timeAdjusted: 4,
            timeCounter: 0,
            payout: false,
            initialVisible: new Decimal(6000),
            upgradeMult: 1,
            upgradeAdd: 0,
            revealed: false,
            overlays: [],
        }, {
            name: "Pizza Delivery",
            desc: "desc1",
            owned: 0,
            incomeType: "money",
            incomeBase: new Decimal(1250),
            costType: "money",
            costBase: new Decimal(10000),
            costCoef: 1.13,
            timeBase: 8,
            timeAdjusted: 8,
            timeCounter: 0,
            payout: false,
            initialVisible: new Decimal(15000),
            upgradeMult: 1,
            upgradeAdd: 0,
            revealed: false,
            overlays: [],
        }, {
            name: "Donut Shop",
            desc: "desc2",
            owned: 0,
            incomeType: "money",
            incomeBase: new Decimal(1200),
            costType: "money",
            costBase: new Decimal(150000),
            costCoef: 1.12,
            timeBase: 16,
            timeAdjusted: 16,
            timeCounter: 0,
            payout: false,
            initialVisible: new Decimal(999999999999999),
            upgradeMult: 1,
            upgradeAdd: 0,
            revealed: false,
            overlays: [],
        }, {
            name: "Shrimp Boat",
            desc: "desc2",
            owned: 0,
            incomeType: "money",
            incomeBase: new Decimal(6000),
            costType: "money",
            costBase: new Decimal(2250000),
            costCoef: 1.11,
            timeBase: 32,
            timeAdjusted: 32,
            timeCounter: 0,
            payout: false,
            initialVisible: new Decimal(999999999999999),
            upgradeMult: 1,
            upgradeAdd: 0,
            revealed: false,
            overlays: [],
        }, {
            name: "Hockey Team",
            desc: "desc2",
            owned: 0,
            incomeType: "money",
            incomeBase: new Decimal(25000),
            costType: "money",
            costBase: new Decimal(25000000),
            costCoef: 1.10,
            timeBase: 64,
            timeAdjusted: 64,
            timeCounter: 0,
            payout: false,
            initialVisible: new Decimal(999999999999999),
            upgradeMult: 1,
            upgradeAdd: 0,
            revealed: false,
            overlays: [],
        }, {
            name: "Movie Studio",
            desc: "desc1",
            owned: 0,
            incomeType: "money",
            incomeBase: new Decimal(90000),
            costType: "money",
            costBase: new Decimal(250000000),
            costCoef: 1.09,
            timeBase: 128,
            timeAdjusted: 128,
            timeCounter: 0,
            payout: false,
            initialVisible: new Decimal(999999999999999),
            upgradeMult: 1,
            upgradeAdd: 0,
            revealed: false,
            overlays: [],
        }, {
            name: "Bank",
            desc: "desc2",
            owned: 0,
            incomeType: "money",
            incomeBase: new Decimal(250000),
            costType: "money",
            costBase: new Decimal(2500000000),
            costCoef: 1.08,
            timeBase: 256,
            timeAdjusted: 256,
            timeCounter: 0,
            payout: false,
            initialVisible: new Decimal(999999999999999),
            upgradeMult: 1,
            upgradeAdd: 0,
            revealed: false,
            overlays: [],
        }, {
            name: "Oil Company",
            desc: "desc2",
            owned: 0,
            incomeType: "money",
            incomeBase: new Decimal(900000),
            costType: "money",
            costBase: new Decimal(25000000000),
            costCoef: 1.07,
            timeBase: 1024,
            timeAdjusted: 1024,
            timeCounter: 0,
            payout: false,
            initialVisible: new Decimal(999999999999999),
            upgradeMult: 1,
            upgradeAdd: 0,
            revealed: false,
            overlays: [],
        }
    ]);

}