// import { Decimal } from 'decimal.js';
const Decimal = require('decimal.js');

export default function UpgradeInit() {

    return ([
        // {
        //     id: 0,
        //     name: "0/1",
        //     watchType: "money",
        //     watchValue: new Decimal("2e3"),
        //     costType: "money",
        //     costValue: new Decimal("10.38e3"),
        //     // costValue: new Decimal("50"),
        //     rewardType: "upgradeMult",
        //     rewardTarget: 0,
        //     rewardValue: 5,
        // },
        // {
        //     id: 100,
        //     name: "1/1",
        //     watchType: "money",
        //     watchValue: new Decimal("70e3"),
        //     costType: "money",
        //     costValue: new Decimal("207.6e3"),
        //     rewardType: "upgradeMult",
        //     rewardTarget: 1,
        //     rewardValue: 5,
        // },
        // {
        //     id: 200,
        //     name: "2/1",
        //     watchType: "money",
        //     watchValue: new Decimal("1.2e6"),
        //     costType: "money",
        //     costValue: new Decimal("4.17e6"),
        //     rewardType: "upgradeMult",
        //     rewardTarget: 2,
        //     rewardValue: 5,
        // },
        // {
        //     id: 300,
        //     name: "3/1",
        //     watchType: "money",
        //     watchValue: new Decimal("28e6"),
        //     costType: "money",
        //     costValue: new Decimal("83e6"),
        //     rewardType: "upgradeMult",
        //     rewardTarget: 3,
        //     rewardValue: 5,
        // },
        // {
        //     id: 400,
        //     name: "4/1",
        //     watchType: "money",
        //     watchValue: new Decimal("550e6"),
        //     costType: "money",
        //     costValue: new Decimal("1.66e9"),
        //     rewardType: "upgradeMult",
        //     rewardTarget: 4,
        //     rewardValue: 5,
        // },
        // {
        //     id: 500,
        //     name: "5/1",
        //     watchType: "money",
        //     watchValue: new Decimal("11e9"),
        //     costType: "money",
        //     costValue: new Decimal("33.3e9"),
        //     rewardType: "upgradeMult",
        //     rewardTarget: 5,
        //     rewardValue: 5,
        // },
        // {
        //     id: 600,
        //     name: "6/1",
        //     watchType: "money",
        //     watchValue: new Decimal("223e9"),
        //     costType: "money",
        //     costValue: new Decimal("668.6e9"),
        //     rewardType: "upgradeMult",
        //     rewardTarget: 6,
        //     rewardValue: 5,
        // },
        // {
        //     id: 700,
        //     name: "7/1",
        //     watchType: "money",
        //     watchValue: new Decimal("4.1e12"),
        //     costType: "money",
        //     costValue: new Decimal("13.43e12"),
        //     rewardType: "upgradeMult",
        //     rewardTarget: 7,
        //     rewardValue: 5,
        // },
        // {
        //     id: 800,
        //     name: "8/1",
        //     watchType: "money",
        //     watchValue: new Decimal("21e12"),
        //     costType: "money",
        //     costValue: new Decimal("63.1e12"),
        //     rewardType: "upgradeMult",
        //     rewardTarget: 8,
        //     rewardValue: 5,
        // },
        // {
        //     id: 900,
        //     name: "9/1",
        //     watchType: "money",
        //     watchValue: new Decimal("400e12"),
        //     costType: "money",
        //     costValue: new Decimal("1.27e15"),
        //     rewardType: "upgradeMult",
        //     rewardTarget: 9,
        //     rewardValue: 5,
        // },


        {
            id: 5000,
            name: "New Technology",
            watchType: "businessOwned",
            watchTarget: 0,
            watchValue: 1,
            costType: "money",
            costValue: new Decimal("100"),
            rewardType: "enableFeature",
            rewardTarget: "Satellite",
        }, {
            id: 5001,
            name: "New Technology",
            watchType: "businessOwned",
            watchTarget: 0,
            watchValue: 1,
            costType: "money",
            costValue: new Decimal("100"),
            rewardType: "enableFeature",
            rewardTarget: "Self-Replication Machinery",
        }, {
            id: 5002,
            name: "New Technology",
            watchType: "businessOwned",
            watchTarget: 6,
            watchValue: 100,
            costType: "money",
            costValue: new Decimal("1e12"),
            rewardType: "enableFeature",
            rewardTarget: "Nano Technology",
        }, {
            id: 5003,
            name: "New Technology",
            watchType: "businessOwned",
            watchTarget: 0,
            watchValue: 1,
            costType: "money",
            costValue: new Decimal("100"),
            rewardType: "enableFeature",
            rewardTarget: "Quality Control",
        }, {
            id: 5004,
            name: "New Technology",
            watchType: "businessOwned",
            watchTarget: 0,
            watchValue: 1,
            costType: "money",
            costValue: new Decimal("100"),
            rewardType: "enableFeature",
            rewardTarget: "Combat",
        }, {
            id: 10000,
            name: "New Ability",
            watchType: "businessOwned",
            watchTarget: 0,
            watchValue: 1,
            costType: "money",
            costValue: new Decimal("100"),
            rewardType: "enableFeature",
            rewardTarget: "Probe Autobuy",
        }

    ]);
}